class MC
{
  String? fn,ln,edu,birth,age,gender,status,occ,pn,email,add,zc,country,state,city,height,weight,hobby,skill1,skill2,skill3,otherskill,summary,expe,image;
  MC(
        {
          this.fn,
          this.ln,
          this.edu,
          this.birth,
          this.age,
          this.gender,
          this.status,
          this.occ,
          this.pn,
          this.email,
          this.add,
          this.zc,
          this.country,
          this.state,
          this.city,
          this.height,
          this.weight,
          this.hobby,
          this.skill1,
          this.skill2,
          this.skill3,
          this.otherskill,
          this.summary,
          this.expe,
          this.image,
        }
     );
}